version: "3"
services:
  elk:
    image: prima/filebeat:6.4.2
    container_name: filebeat
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./filebeat.yml:/filebeat.yml
      - ./logs:/home/logs
    networks:
      - server_default # 本地测试的时候，这里需要添加网络设置， server_default 是由服务端 server 目录下 docker-compose up 起服务时自动创建的网络

networks:
  server_default: # 本地测试的时候，这里需要添加网络设置， server_default 是由服务端 server 目录下 docker-compose up 起服务时自动创建的网络
    external: true
