#filebeat.modules:
#  - module: system
filebeat.prospectors:
  - input_type: log
    paths:
      - /home/logs/laravel/*.log
    # document_type 可能因为 Filebeat版本问题需要更新，用 fileds 字段处理
    document_type: "laravel"
    # laravel 日志多行合并配置
    multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after

  - input_type: log
    paths:
      - /home/logs/*.log
output.logstash:
  hosts: ["172.17.0.2:5044"]
#filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
